namespace CleanserBlazorUI.Constants;
public class SpreadSheetHeadersData
{
    public static List<string> Individual = new List<string>
    {
        "Data","CorrectionIndicator","CreditFacilityAccNum","CustomerID","BranchCode","NatIDNum","VotersIDNum","DriverLicNum","PassportNum","SSNum","EzwichNum","OtherIDType","OtherIDNum","TINum","Gender","MaritalStatus","Nationality","DateOfBirth","Title","Surname","FirstName","MiddleNames","PreviousNames","Alias","ProofOfAddType","ProofOfAddNum","CurResAddr1","CurResAddr2","CurResAddr3","CurResAddr4","CurResAddrPostalCode","DateMovedCurrRes","PrevResAddr1","PrevResAddr2","PrevResAddr3","PrevResAddr4","PrevResAddrPostalCode","OwnerOrTenant","PostAddrLine1","PostAddrLine2","PostAddrLine3","PostAddrLine4","PostalAddPostCode","EmailAddress","HomeTel","MobileTel1","MobileTel2","WorkTel","NumOfDependants","EmpType","EmpPayrollNum","Paypoint","EmpName","EmpAddr1","EmpAddr2","EmpAddr3","EmpAddr4","EmpAddrPostalCode","DateOfEmp","Occupation","IncomeCurrency","Income","JointOrSoleAcc","NoParticipantsInAcc","OldCustomerID","OldAccountNum","OldSRN","OldBranchCode","CreditFacilityType","PurposeOfFacility","FacilityTerm","DefPaymentStartDate","AmountCurrency","FacilityAmount","DisbursementDate","DisbursementAmt","MaturityDate","SchdInstalAmount","RepaymentFreq","LastPaymentAmount","LastPaymentDate","NextPaymentDate","CurBal","CurBalIndicator","AssetClassification","AmountInArrears","ArrearsStartDate","NDIA","PaymentHistoryProfile","AmtOverdue1to30days","AmtOverdue31to60days","AmtOverdue61to90days","AmtOverdue91to120days","AmtOverdue121to150days","AmtOverdue151to180days","AmtOverdue181orMore","LegalFlag","FacilityStatusCode","FacilityStatusDate","ClosedDate","ClosureReason","WrittenOffAmt","ReasonForWrittenOff","DateRestructured","ReasonForRestructure","CreditCollateralInd","SecurityType","NatureOfCharge","SecurityValue","CollRegRefNum","SpecialCommentsCode","NatureOfGuarantor","NameOfComGuarantor","BusRegOfGuarantor","G1Surname","G1FirstName","G1MiddleNames","G1NatID","G1VotID","G1DrivLic","G1PassNum","G1SSN","G1Gender","G1DOB","G1Add1","G1Add2","G1Add3","G1HomeTel","G1WorkTel","G1Mobile","G2Surname","G2FirstName","G2MiddleNames","G2NatID","G2VotID","G2DrivLic","G2PassNum","G2SSN","G2Gender","G2DOB","G2Add1","G2Add2","G2Add3","G2HomeTel","G2WorkTel","G2Mobile","G3Surname","G3FirstName","G3MiddleNames","G3NatID","G3VotID","G3DrivLic","G3PassNum","G3SSN","G3Gender","G3DOB","G3Add1","G3Add2","G3Add3","G3HomeTel","G3WorkTel","G3Mobile","G4Surname","G4FirstName","G4MiddleNames","G4NatID","G4VotID","G4DrivLic","G4PassNum","G4SSN","G4Gender","G4DOB","G4Add1","G4Add2","G4Add3","G4HomeTel","G4WorkTel","G4Mobile"
    };
    public static List<string> Business = new List<string>
    {
        "Data","CorrectionIndicator","Facilityaccnum","CustomerID","Branchcode","Busregnum","Prevregnum","Tinum","Sectorindcode","Subsecindcode","Bustype","Registrationdate","Commencementdate","Businessname","Tradingname","Turnovercurrency","Turnoveramount","Prevbusname","Proofofaddtype","Proofofaddnum","Curlocadd1","Curlocadd2","Curlocadd3","Curlocadd4","Curlocaddrpostalcode","Postaddrline1","Postaddrline2","Postaddrline3","Postaddrline4","Postaladdpostcode","Websiteadd","Emailaddress","Officetel1","Officetel2","Officefaxnum","Oldcustomerid","Oldaccountnum","Oldsrn","Oldbranchcode","Creditfacilitytype","Purposeoffacility","Facilityterm","Defpaymentstartdate","Amountcurrency","Facilityamount","Disbursementdate","Disbursementamt","Maturitydate","Schdinstalamount","Repaymentfreq","Lastpaymentamount","Lastpaymentdate","Nextpaymentdate","Curbal","Curbalindicator","Assetclassification","Amountinarrears","Arrearsstartdate","Ndia","Paymenthistoryprofile","Amtoverdue1To30Days","Amtoverdue31To60Days","Amtoverdue61To90Days","Amtoverdue91To120Days","Amtoverdue121To150Days","Amtoverdue151To180Days","AmtOverdue181orMore","Legalflag","Facilitystatuscode","Facilitystatusdate","Closeddate","Closurereason","Writtenoffamt","Reasonforwrittenoff","Daterestructured","Reasonforrestructure","Creditcollateralind","Securitytype","Natureofcharge","Securityvalue","Collregrefnum","Specialcommentscode","Natureofguarantor1","Nameofcomguarantor1","Busregofguarantor1","G1Surname","G1Firstname","G1Middlenames","G1Natid","G1Votid","G1Drivlic","G1Passnum","G1Ssn","G1Gender","G1Dob","G1Add1","G1Add2","G1Add3","G1Hometel","G1Worktel","G1Mobile","Natureofguarantor2","Nameofcomguarantor2","Busregofguarantor2","G2Surname","G2Firstname","G2Middlenames","G2Natid","G2Votid","G2Drivlic","G2Passnum","G2Ssn","G2Gender","G2Dob","G2Add1","G2Add2","G2Add3","G2Hometel","G2Worktel","G2Mobile","Natureofguarantor3","Nameofcomguarantor3","Busregofguarantor3","G3Surname","G3Firstname","G3Middlenames","G3Natid","G3Votid","G3Drivlic","G3Passnum","G3Ssn","G3Gender","G3Dob","G3Add1","G3Add2","G3Add3","G3Hometel","G3Worktel","G3Mobile","Natureofguarantor4","Nameofcomguarantor4","Busregofguarantor4","G4Surname","G4Firstname","G4Middlenames","G4Natid","G4Votid","G4Drivlic","G4Passnum","G4Ssn","G4Gender","G4Dob","G4Add1","G4Add2","G4Add3","G4Hometel","G4Worktel","G4Mobile"
    };
    public static List<string> IndividualDud = new List<string>
    {
        "Data","CorrectionIndicator","CreditFacilityAccNum","CustomerID","BranchCode","NatIDNum","VotersIDNum","DriverLicNum","PassportNum","SSNum","EzwichNum","OtherIDType","OtherIDNum","TINum","Gender","MaritalStatus","Nationality","DateOfBrith","Title","Surname","FirstName","MiddleNames","PreviousNames","Alias","ProofOfAddType","ProofOfAddNum","CurResAddr1","CurResAddr2","CurResAddr3","CurResAddr4","CurResAddrPostalCode","DateMovedCurrRes","PrevResAddr1","PrevResAddr2","PrevResAddr3","PrevResAddr4","PrevResAddrPostalCode","OwnerOrTenant","PostAddrLine1","PostAddrLine2","PostAddrLine3","PostAddrLine4","PostalAddPostCode","EmailAddress","HomeTel","MobileTel1","MobileTel2","WorkTel","NumOfDependants","EmpType","EmpPayrollNum","EmpName","EmpAddr1","EmpAddr2","EmpAddr3","EmpAddr4","EmpAddrPostalCode","DateOfEmp","Occupation","IncomeCurrency","Income","JointOrSoleAcc","NoParticipantsInAcc","OldCustomerID","OldAccountNum","OldSRN","OldBranchCode","ChequeNumber","DateAccountOpened","DateIssued","DateBounced","ReasonReturned","Currency","ChequeAmount"
    };
    public static List<string> BusinessDud = new List<string>
    {
        "Data","Correctionindicator","Facilityaccnum","CustomerID","Branchcode","Busregnum","Prevregnum","Tinum","Sectorindcode","Subsecindcode","Bustype","Registrationdate","Commencementdate","Businessname","Tradingname","Turnovercurrency","Turnoveramount","Prevbusname","Proofofaddtype","Proofofaddnum","Curlocadd1","Curlocadd2","Curlocadd3","Curlocadd4","Curlocaddrpostalcode","Postaddrline1","Postaddrline2","Postaddrline3","Postaddrline4","Postaladdpostcode","Websiteadd","Emailaddress","Officetel1","Officetel2","Officefaxnum","Oldcustomerid","Oldaccountnum","Oldsrn","Oldbranchcode","ChequeNumber","DateAccountOpened","DateIssued","DateBounced","ReasonReturned","Currency","ChequeAmount"
    };

}